version: "3.7"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - dbdata:/var/lib/mongodb
    ports:
      - 27017:27017
    networks:
      - webnet
  memcached:
    image:  memcached:latest
    ports:
      - 11211:11211
    networks:
      - webnet
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
      target: runnable
    depends_on:
      - mongodb
      - memcached
    volumes:
      - podata:/mnt/podata
      - type: tmpfs
        target: /mnt/podata/mnt
      - type: bind
        source: ../
        target: /opt/product-opener/
      - product_images:/opt/product-opener/html/images/products
      - type: bind
        source: ./backend-dev/conf/Config.pm
        target: /opt/product-opener/lib/ProductOpener/Config.pm
      - type: bind
        source: ./backend-dev/conf/Config2.pm
        target: /opt/product-opener/lib/ProductOpener/Config2.pm
      - type: bind
        source: ./backend-dev/conf/log.conf
        target: /mnt/podata/log.conf
      - type: bind
        source: ./backend-dev/conf/apache.conf
        target: /usr/local/apache2/conf/sites-enabled/product-opener.conf
      - type: bind
        source: ./backend-dev/conf/po-foreground.sh
        target: /usr/local/bin/po-foreground.sh
    command: ["/bin/sh", "/usr/local/bin/po-foreground.sh"]
    ports:
      - 80
    networks:
      - webnet
  frontend:
    image: nginx:latest
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ../
        target: /opt/product-opener/
      - product_images:/opt/product-opener/html/images/products
      - type: bind
        source: ./frontend-git/conf/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - webnet
networks:
  webnet:
volumes:
  dbdata:
  podata:
  product_images:
